import "./styles/normalise.css";
import "./styles/main_styles.css";

import MyButton from "./components/MyButton";

function App() {
  return (
    <div className="main_container">
      <div className="section1">
        <img
          src="./images/space.png"
          alt="Star filled dark night sky."
          className="space"
        />
        <img
          src="./images/earth.png"
          alt="Planet earth with a tilt showing Europe and Africa."
          className="earth"
        />
        <img
          src="./images/planet.png"
          alt="A planet resembling a simplified Saturn."
          className="planet"
        />
        <img
          src="./images/rocket.png"
          alt="A playful representation of a space rocket."
          className="rocket"
        />
        <img
          src="./images/satellite.png"
          alt="A space satellite in orbit."
          className="satellite"
        />
        <div className="greeting">[Welcome]</div>
      </div>

      <div className="section2">
        <svg
          className="svg_curve_top"
          xmlns="http://www.w3.org/2000/svg"
          fill="orange"
          viewBox="0 0 100 100"
          preserveAspectRatio="none"
        >
          <path d="M0,100 C65,93 76,10 100,100" />
        </svg>

        <div className="section2_container">
          <div className="left_side">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero,
              deserunt at! Debitis, deleniti eos voluptatibus quis, hic
              molestiae nulla sunt, pariatur dolores possimus recusandae odit
              deserunt dignissimos veniam tempore quaerat?
            </p>
          </div>
          <div className="right_side">
            <img
              src="https://picsum.photos/1200/1200"
              alt="Randomly generated by API call, unable to know contents."
              className="image"
            />
          </div>
        </div>

        <svg
          className="svg_curve_bottom"
          xmlns="http://www.w3.org/2000/svg"
          fill="orange"
          viewBox="0 0 100 100"
          preserveAspectRatio="none"
        >
          <path d="M0,0 C65,20 90,5 100,0" />
        </svg>
      </div>

      <div className="section3">
        Sign up for our newsletter!
        <input type="text" name="email" id="email" className="input_email" />
        <MyButton name="Sign Up" />
        <div className="contacts">
          <div className="contact_section">
            <ul>
              <li>Affiliates</li>
              <li>Careers</li>
              <li>Privacy</li>
            </ul>
          </div>
          <div className="contact_section">
            <ul>
              <li>
                Telephone <i className="fas fa-phone-square-alt"></i>
              </li>
              <li>
                Email <i className="fas fa-envelope-square"></i>
              </li>
            </ul>
          </div>
          <div className="contact_section">
            <ul>
              <li>
                Instagram <i className="fab fa-instagram-square"></i>
              </li>
              <li>
                Twitter <i className="fab fa-twitter-square"></i>
              </li>
              <li>
                Facebook <i className="fab fa-facebook-square"></i>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
